# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 18:52
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def fill_program_slug_field(apps, schema_editor):
    Program = apps.get_model('songs', 'Program')

    for program in Program.objects.all():
        program.slug = slugify(program.name)
        program.save()


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interlude',
            options={'get_latest_by': 'episode__date'},
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.RunPython(fill_program_slug_field),
    ]
