# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 22:21
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def fill_artist_slug_field(apps, schema_editor):
    Artist = apps.get_model('songs', 'Artist')

    for artist in Artist.objects.all():
        if not artist.name:
            artist.name = 'unknown artist'
        artist.slug = slugify(artist.name)
        artist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_program_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterModelOptions(
            name='interlude',
            options={'get_latest_by': 'episode__date', 'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.RunPython(fill_artist_slug_field),
    ]
