# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_artist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='href',
            field=models.URLField(blank=True),
        ),
    ]
