# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_program_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
