# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_artist_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='preview',
            field=models.URLField(blank=True),
        ),
    ]
