# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_thumbnail_and_preview_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
